In [2]:
import kagglehub
path = kagglehub.dataset_download("PROPPG-PPG/hourly-weather-surface-brazil-southeast-region")

print("Path to dataset files:", path)

Resuming download from 284164096 bytes (1409860919 bytes left)...
Resuming download to /Users/yazid/.cache/kagglehub/datasets/PROPPG-PPG/hourly-weather-surface-brazil-southeast-region/9.archive (284164096/1694025015) bytes left.

100%|██████████| 1.58G/1.58G [03:55<00:00, 5.98MB/s]

Extracting files...

Path to dataset files: /Users/yazid/.cache/kagglehub/datasets/PROPPG-PPG/hourly-weather-surface-brazil-southeast-region/versions/9

In [10]:
import os
print(os.listdir("../data_brazilian"))

['metrics.py', 'southeast.csv', 'columns_description.csv', 'make_dataset.py', 'northeast.csv', 'stations.csv', 'south.csv', 'central_west.csv', 'north.csv']

In [14]:
import pandas as pd
df = pd.read_csv("../data_brazilian/southeast.csv")
print(df.shape)
print(df.columns.tolist())
df.head()

(15345216, 27)
['index', 'Data', 'Hora', 'PRECIPITAÇÃO TOTAL, HORÁRIO (mm)', 'PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)', 'PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB)', 'PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB)', 'RADIACAO GLOBAL (Kj/m²)', 'TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)', 'TEMPERATURA DO PONTO DE ORVALHO (°C)', 'TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C)', 'TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C)', 'TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C)', 'TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C)', 'UMIDADE REL. MAX. NA HORA ANT. (AUT) (%)', 'UMIDADE REL. MIN. NA HORA ANT. (AUT) (%)', 'UMIDADE RELATIVA DO AR, HORARIA (%)', 'VENTO, DIREÇÃO HORARIA (gr) (° (gr))', 'VENTO, RAJADA MAXIMA (m/s)', 'VENTO, VELOCIDADE HORARIA (m/s)', 'region', 'state', 'station', 'station_code', 'latitude', 'longitude', 'height']

,index,Data,Hora,"PRECIPITAÇÃO TOTAL, HORÁRIO (mm)","PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)",PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB),PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB),RADIACAO GLOBAL (Kj/m²),"TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)",TEMPERATURA DO PONTO DE ORVALHO (°C),...,"VENTO, DIREÇÃO HORARIA (gr) (° (gr))","VENTO, RAJADA MAXIMA (m/s)","VENTO, VELOCIDADE HORARIA (m/s)",region,state,station,station_code,latitude,longitude,height
0,0,2000-05-07,00:00,-9999.0,-9999.0,-9999.0,-9999.0,-9999,-9999.0,-9999.0,...,-9999,-9999.0,-9999.0,SE,RJ,ECOLOGIA AGRICOLA,A601,-22.8,-43.683333,33.0
1,1,2000-05-07,01:00,-9999.0,-9999.0,-9999.0,-9999.0,-9999,-9999.0,-9999.0,...,-9999,-9999.0,-9999.0,SE,RJ,ECOLOGIA AGRICOLA,A601,-22.8,-43.683333,33.0
2,2,2000-05-07,02:00,-9999.0,-9999.0,-9999.0,-9999.0,-9999,-9999.0,-9999.0,...,-9999,-9999.0,-9999.0,SE,RJ,ECOLOGIA AGRICOLA,A601,-22.8,-43.683333,33.0
3,3,2000-05-07,03:00,-9999.0,-9999.0,-9999.0,-9999.0,-9999,-9999.0,-9999.0,...,-9999,-9999.0,-9999.0,SE,RJ,ECOLOGIA AGRICOLA,A601,-22.8,-43.683333,33.0
4,4,2000-05-07,04:00,-9999.0,-9999.0,-9999.0,-9999.0,-9999,-9999.0,-9999.0,...,-9999,-9999.0,-9999.0,SE,RJ,ECOLOGIA AGRICOLA,A601,-22.8,-43.683333,33.0

In [15]:
df = df.replace(-9999, pd.NA)
df = df.replace(-9999.0, pd.NA)

In [27]:
df['timestamp'] = pd.to_datetime(df['Data'] + ' ' + df['Hora'], errors='coerce')
df_final = df[(df['timestamp'] >= '2020-01-01') & (df['timestamp'] <= '2021-12-31')]
print(df_final.shape)

(1737936, 28)

In [29]:
df_final.head()

,index,Data,Hora,"PRECIPITAÇÃO TOTAL, HORÁRIO (mm)","PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)",PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB),PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB),RADIACAO GLOBAL (Kj/m²),"TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)",TEMPERATURA DO PONTO DE ORVALHO (°C),...,"VENTO, RAJADA MAXIMA (m/s)","VENTO, VELOCIDADE HORARIA (m/s)",region,state,station,station_code,latitude,longitude,height,timestamp
13607280,0,2020-12-12,21:00,0.0,909.8,910.0,909.7,103,22.1,19.2,...,6.6,2.3,SE,MG,BURITIS,A544,-15.524167,-46.435556,894.0,2020-12-12 21:00:00
13607281,1,2020-12-12,22:00,0.0,910.9,910.9,909.8,26,21.8,19.6,...,4.4,2.7,SE,MG,BURITIS,A544,-15.524167,-46.435556,894.0,2020-12-12 22:00:00
13607282,2,2020-12-12,23:00,0.0,911.4,911.5,910.9,<NA>,21.4,18.9,...,5.1,3.9,SE,MG,BURITIS,A544,-15.524167,-46.435556,894.0,2020-12-12 23:00:00
13607283,3,2020-12-13,00:00,0.0,911.5,911.6,911.4,<NA>,20.6,18.5,...,5.0,2.7,SE,MG,BURITIS,A544,-15.524167,-46.435556,894.0,2020-12-13 00:00:00
13607284,4,2020-12-13,01:00,0.0,912.0,912.0,911.5,<NA>,19.8,18.1,...,4.0,0.9,SE,MG,BURITIS,A544,-15.524167,-46.435556,894.0,2020-12-13 01:00:00

In [30]:
stations = df_final['station_code'].unique()
print(len(stations))
print(df_final.dtypes)

149
index                                                             int64
Data                                                             object
Hora                                                             object
PRECIPITAÇÃO TOTAL, HORÁRIO (mm)                                 object
PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)            object
PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB)                  object
PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB)                 object
RADIACAO GLOBAL (Kj/m²)                                          object
TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)                     object
TEMPERATURA DO PONTO DE ORVALHO (°C)                             object
TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C)                       object
TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C)                       object
TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C)                 object
TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C)                 object
UMIDADE REL. MAX. NA HORA ANT. (AUT) (%)                         object
UMIDADE REL. MIN. NA HORA ANT. (AUT) (%)                         object
UMIDADE RELATIVA DO AR, HORARIA (%)                              object
VENTO, DIREÇÃO HORARIA (gr) (° (gr))                             object
VENTO, RAJADA MAXIMA (m/s)                                       object
VENTO, VELOCIDADE HORARIA (m/s)                                  object
region                                                           object
state                                                            object
station                                                          object
station_code                                                     object
latitude                                                        float64
longitude                                                       float64
height                                                           object
timestamp                                                datetime64[ns]
dtype: object

In [33]:
weather_cols = [c for c in df_final.columns if c not in ['index','height', 'Data', 'Hora', 'timestamp', 
                                                             'region', 'state', 'station', 
                                                             'station_code', 'latitude', 'longitude', 'height']]

for col in weather_cols:
    df_final[col] = df_final[col].astype(str).str.replace(',', '.', regex=False)
    df_final[col] = pd.to_numeric(df_final[col], errors='coerce')

/var/folders/57/m7vffbyx1v1555z3rc8_wg640000gn/T/ipykernel_27202/948220053.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final[col] = df_final[col].astype(str).str.replace(',', '.', regex=False)
/var/folders/57/m7vffbyx1v1555z3rc8_wg640000gn/T/ipykernel_27202/948220053.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final[col] = pd.to_numeric(df_final[col], errors='coerce')
/var/folders/57/m7vffbyx1v1555z3rc8_wg640000gn/T/ipykernel_27202/948220053.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final[col] = df_final[col].astype(str).str.replace(',', '.', regex=False)
/var/folders/57/m7vffbyx1v1555z3rc8_wg640000gn/T/ipykernel_27202/948220053.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final[col] = pd.to_numeric(df_final[col], errors='coerce')
/var/folders/57/m7vffbyx1v1555z3rc8_wg640000gn/T/ipykernel_27202/948220053.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final[col] = df_final[col].astype(str).str.replace(',', '.', regex=False)
/var/folders/57/m7vffbyx1v1555z3rc8_wg640000gn/T/ipykernel_27202/948220053.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final[col] = pd.to_numeric(df_final[col], errors='coerce')
/var/folders/57/m7vffbyx1v1555z3rc8_wg640000gn/T/ipykernel_27202/948220053.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final[col] = df_final[col].astype(str).str.replace(',', '.', regex=False)
/var/folders/57/m7vffbyx1v1555z3rc8_wg640000gn/T/ipykernel_27202/948220053.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final[col] = pd.to_numeric(df_final[col], errors='coerce')
/var/folders/57/m7vffbyx1v1555z3rc8_wg640000gn/T/ipykernel_27202/948220053.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final[col] = df_final[col].astype(str).str.replace(',', '.', regex=False)
/var/folders/57/m7vffbyx1v1555z3rc8_wg640000gn/T/ipykernel_27202/948220053.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final[col] = pd.to_numeric(df_final[col], errors='coerce')
/var/folders/57/m7vffbyx1v1555z3rc8_wg640000gn/T/ipykernel_27202/948220053.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final[col] = df_final[col].astype(str).str.replace(',', '.', regex=False)
/var/folders/57/m7vffbyx1v1555z3rc8_wg640000gn/T/ipykernel_27202/948220053.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final[col] = pd.to_numeric(df_final[col], errors='coerce')
/var/folders/57/m7vffbyx1v1555z3rc8_wg640000gn/T/ipykernel_27202/948220053.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final[col] = df_final[col].astype(str).str.replace(',', '.', regex=False)
/var/folders/57/m7vffbyx1v1555z3rc8_wg640000gn/T/ipykernel_27202/948220053.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final[col] = pd.to_numeric(df_final[col], errors='coerce')
/var/folders/57/m7vffbyx1v1555z3rc8_wg640000gn/T/ipykernel_27202/948220053.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final[col] = df_final[col].astype(str).str.replace(',', '.', regex=False)
/var/folders/57/m7vffbyx1v1555z3rc8_wg640000gn/T/ipykernel_27202/948220053.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final[col] = pd.to_numeric(df_final[col], errors='coerce')
/var/folders/57/m7vffbyx1v1555z3rc8_wg640000gn/T/ipykernel_27202/948220053.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final[col] = df_final[col].astype(str).str.replace(',', '.', regex=False)
/var/folders/57/m7vffbyx1v1555z3rc8_wg640000gn/T/ipykernel_27202/948220053.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final[col] = pd.to_numeric(df_final[col], errors='coerce')
/var/folders/57/m7vffbyx1v1555z3rc8_wg640000gn/T/ipykernel_27202/948220053.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final[col] = df_final[col].astype(str).str.replace(',', '.', regex=False)
/var/folders/57/m7vffbyx1v1555z3rc8_wg640000gn/T/ipykernel_27202/948220053.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final[col] = pd.to_numeric(df_final[col], errors='coerce')
/var/folders/57/m7vffbyx1v1555z3rc8_wg640000gn/T/ipykernel_27202/948220053.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final[col] = df_final[col].astype(str).str.replace(',', '.', regex=False)
/var/folders/57/m7vffbyx1v1555z3rc8_wg640000gn/T/ipykernel_27202/948220053.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final[col] = pd.to_numeric(df_final[col], errors='coerce')
/var/folders/57/m7vffbyx1v1555z3rc8_wg640000gn/T/ipykernel_27202/948220053.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final[col] = df_final[col].astype(str).str.replace(',', '.', regex=False)
/var/folders/57/m7vffbyx1v1555z3rc8_wg640000gn/T/ipykernel_27202/948220053.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final[col] = pd.to_numeric(df_final[col], errors='coerce')
/var/folders/57/m7vffbyx1v1555z3rc8_wg640000gn/T/ipykernel_27202/948220053.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final[col] = df_final[col].astype(str).str.replace(',', '.', regex=False)
/var/folders/57/m7vffbyx1v1555z3rc8_wg640000gn/T/ipykernel_27202/948220053.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final[col] = pd.to_numeric(df_final[col], errors='coerce')
/var/folders/57/m7vffbyx1v1555z3rc8_wg640000gn/T/ipykernel_27202/948220053.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final[col] = df_final[col].astype(str).str.replace(',', '.', regex=False)
/var/folders/57/m7vffbyx1v1555z3rc8_wg640000gn/T/ipykernel_27202/948220053.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final[col] = pd.to_numeric(df_final[col], errors='coerce')
/var/folders/57/m7vffbyx1v1555z3rc8_wg640000gn/T/ipykernel_27202/948220053.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final[col] = df_final[col].astype(str).str.replace(',', '.', regex=False)
/var/folders/57/m7vffbyx1v1555z3rc8_wg640000gn/T/ipykernel_27202/948220053.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final[col] = pd.to_numeric(df_final[col], errors='coerce')
/var/folders/57/m7vffbyx1v1555z3rc8_wg640000gn/T/ipykernel_27202/948220053.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final[col] = df_final[col].astype(str).str.replace(',', '.', regex=False)
/var/folders/57/m7vffbyx1v1555z3rc8_wg640000gn/T/ipykernel_27202/948220053.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final[col] = pd.to_numeric(df_final[col], errors='coerce')
/var/folders/57/m7vffbyx1v1555z3rc8_wg640000gn/T/ipykernel_27202/948220053.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final[col] = df_final[col].astype(str).str.replace(',', '.', regex=False)
/var/folders/57/m7vffbyx1v1555z3rc8_wg640000gn/T/ipykernel_27202/948220053.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final[col] = pd.to_numeric(df_final[col], errors='coerce')

In [34]:
print(df_final.dtypes)

index                                                             int64
Data                                                             object
Hora                                                             object
PRECIPITAÇÃO TOTAL, HORÁRIO (mm)                                float64
PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)           float64
PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB)                 float64
PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB)                float64
RADIACAO GLOBAL (Kj/m²)                                         float64
TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)                    float64
TEMPERATURA DO PONTO DE ORVALHO (°C)                            float64
TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C)                      float64
TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C)                      float64
TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C)                float64
TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C)                float64
UMIDADE REL. MAX. NA HORA ANT. (AUT) (%)                        float64
UMIDADE REL. MIN. NA HORA ANT. (AUT) (%)                        float64
UMIDADE RELATIVA DO AR, HORARIA (%)                             float64
VENTO, DIREÇÃO HORARIA (gr) (° (gr))                            float64
VENTO, RAJADA MAXIMA (m/s)                                      float64
VENTO, VELOCIDADE HORARIA (m/s)                                 float64
region                                                           object
state                                                            object
station                                                          object
station_code                                                     object
latitude                                                        float64
longitude                                                       float64
height                                                           object
timestamp                                                datetime64[ns]
dtype: object

In [35]:
print(df_final[numeric_cols].isna().mean().sort_values(ascending=False) * 100)

index        0.0
latitude     0.0
longitude    0.0
dtype: float64